### PR TITLE
Fix typo, Language-related updates

### PR DESCRIPTION
**Pull request by JellyBrick**

### CODE REVIEW

**Comment by ghost** [comment]
Why do you add logo?
Personally , I think logo is not good.
That's too simple and font is not good...
Maybe producer will make logo!
This is my advice!
So , I don't want to fight with you!
:p___

**Comment by JellyBrick** [comment]
@ZINGDING Removed the logo.

**Comment by ghost** [comment]
@JellyBrick  Ok.

**Comment by HmHmmHm** [comment]
Merged 44e1672b077fc4acad175aff02e409f516c6d3f7

**Pull request merged**
